name: Notify PR events

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Notify to Telegrem
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          disable_web_page_preview: true
          message: |
            ${{ github.event.pull_request.html_url }}

            Title: ${{github.event.pull_request.title}}
            Author: ${{github.actor}}
